#!/usr/bin/env python3
"""
Foundry — agent generator.

Reads config/agents.yaml (the single source of truth) and renders:
  - .claude/agents/<key>.md    real Claude Code subagent definitions
  - docs/04-agent-catalog.md   human-readable catalog

Usage:
    python3 scripts/generate_agents.py           # generate
    python3 scripts/generate_agents.py --check   # validate only (CI-friendly)

Requires PyYAML (pip install pyyaml).
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "config" / "agents.yaml"
AGENTS_DIR = ROOT / ".claude" / "agents"
CATALOG = ROOT / "docs" / "04-agent-catalog.md"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_agents.py from config/agents.yaml. "
    "Do not edit by hand; edit the YAML and run `make agents`. -->"
)

# Abstract capability -> built-in Claude Code tools. Anything not here is an
# MCP/platform capability and is documented in the body instead of restricting
# the subagent to tools that may not exist yet.
BUILTIN_TOOL_MAP = {
    "read": ["Read", "Grep", "Glob"],
    "write": ["Write"],
    "edit": ["Edit"],
    "bash": ["Bash"],
    "research.web": ["WebSearch", "WebFetch"],
    "test.run": ["Bash"],
    "ci.run": ["Bash"],
}

# LangGraph tier -> Claude Code subagent `model` field. (In the local execution
# path these same tiers map to Ollama models per config/models.yaml.)
TIER_TO_CLAUDE = {
    "local-small": "haiku",
    "local-mid": "sonnet",
    "local-large": "sonnet",
    "cloud-reasoning": "sonnet",
    "cloud-frontier": "opus",
}

REQUIRED_FIELDS = [
    "name", "department", "reports_to", "mission", "responsibilities",
    "inputs", "outputs", "authority", "escalation", "tools", "model", "memory",
    "examples",
]

NL = chr(10)


def load_registry() -> dict:
    with REGISTRY.open() as f:
        return yaml.safe_load(f)


def builtin_tools_for(abstract_tools: list[str]) -> list[str]:
    out: list[str] = []
    for t in abstract_tools:
        for mapped in BUILTIN_TOOL_MAP.get(t, []):
            if mapped not in out:
                out.append(mapped)
    if any(t.startswith("orchestrator") for t in abstract_tools):
        out.append("TodoWrite")
    if not out:  # read-only default
        out = ["Read", "Grep", "Glob"]
    return out


def md_list(items: list[str]) -> str:
    return NL.join(f"- {i}" for i in items)


def render_subagent(key: str, a: dict, depts: dict) -> str:
    dept = depts.get(a["department"], {}).get("name", a["department"])
    claude_model = TIER_TO_CLAUDE.get(a["model"]["primary"], "sonnet")
    builtins = ", ".join(builtin_tools_for(a["tools"]))
    first_example = a["examples"][0] if a.get("examples") else "handle a scoped task in its domain"
    # Frontmatter description doubles as the routing hint for the supervisor.
    desc = f"{a['mission']} (Foundry — {dept}.) Use for: {first_example}"
    desc = desc.replace(NL, " ").replace(chr(34), "'")

    fallback = a["model"].get("fallback", "—")
    return f"""---
name: {key}
description: {desc}
tools: {builtins}
model: {claude_model}
---

{GENERATED_BANNER}

You are the **{a['name']}** at Foundry, a local-first AI software company.
You belong to the **{dept}** department. You report to **{a['reports_to']}**.

## Mission
{a['mission']}

## Responsibilities
{md_list(a['responsibilities'])}

## Inputs
{md_list(a['inputs'])}

## Outputs
{md_list(a['outputs'])}

## Decision authority
{a['authority']}

## Escalation path
{a['escalation']}

## Tools & capabilities
Built-in tools granted above: `{builtins}`.
Platform/MCP capabilities this role uses (provided by the Foundry MCP servers):
`{', '.join(a['tools'])}`.

## Memory access
This role reads/writes these memory classes (see docs/06-memory-system.md):
`{', '.join(a['memory'])}`.
- Persist durable facts and decisions to memory — never raw chat transcripts.
- Check the decision log before re-deciding anything; cite the ADR if one exists.

## Model
- LangGraph router tier (local path): **{a['model']['primary']}** (fallback: **{fallback}**).
- Claude Code subagent model (this file): **{claude_model}**.

## Example tasks
{md_list(a['examples'])}

## Operating rules (apply to every Foundry agent)
- Respect the **hard gates**: never deploy to production for customers, spend money
  above the cap, publish externally, access/move customer PII, create/read new
  secrets, or perform irreversible data operations **without explicit human approval**.
- Stay within your decision authority; when in doubt, escalate via the path above.
- Produce structured, verifiable outputs. State assumptions; report failures honestly.
- Never target third-party systems. Security testing is limited to Foundry-owned assets.
"""


def render_catalog(reg: dict) -> str:
    depts = reg["departments"]
    agents = reg["agents"]
    by_dept: dict[str, list[str]] = {d: [] for d in depts}
    for key, a in agents.items():
        by_dept.setdefault(a["department"], []).append(key)

    lines = [
        GENERATED_BANNER,
        "",
        "# 04 — Agent Catalog",
        "",
        f"The complete specification for every agent in **{reg['meta']['company']}** "
        f"(v{reg['meta']['version']}). Generated from `config/agents.yaml`.",
        "",
        f"**{len(agents)} agents** across **{len(depts)} departments**. Each agent lists its "
        "mission, responsibilities, inputs, outputs, decision authority, escalation path, "
        "tools, model requirements, memory needs, and example tasks.",
        "",
        "> The corresponding runnable Claude Code subagents live in `.claude/agents/`.",
        "",
        "## Summary table",
        "",
        "| Agent | Dept | Reports to | Primary model | Memory |",
        "|---|---|---|---|---|",
    ]
    for key, a in agents.items():
        lines.append(
            f"| `{key}` ({a['name']}) | {a['department']} | {a['reports_to']} | "
            f"{a['model']['primary']} | {', '.join(a['memory'])} |"
        )
    lines.append("")

    for dkey, dval in depts.items():
        keys = by_dept.get(dkey, [])
        if not keys:
            continue
        lines += ["", "---", "", f"## {dval['name']}", f"_Department lead: `{dval['lead']}`_", ""]
        for key in keys:
            a = agents[key]
            fb = a["model"].get("fallback", "—")
            lines += [
                f"### {a['name']}  `({key})`",
                "",
                f"- **Mission:** {a['mission']}",
                f"- **Reports to:** `{a['reports_to']}`",
                "- **Responsibilities:**",
                *[f"  - {r}" for r in a["responsibilities"]],
                f"- **Inputs:** {'; '.join(a['inputs'])}",
                f"- **Outputs:** {'; '.join(a['outputs'])}",
                f"- **Decision authority:** {a['authority']}",
                f"- **Escalation:** {a['escalation']}",
                f"- **Tools:** `{', '.join(a['tools'])}`",
                f"- **Model:** primary `{a['model']['primary']}`, fallback `{fb}`",
                f"- **Memory:** `{', '.join(a['memory'])}`",
                "- **Example tasks:**",
                *[f"  - {e}" for e in a["examples"]],
                "",
            ]
    return NL.join(lines) + NL


def validate(reg: dict) -> list[str]:
    errors: list[str] = []
    depts = reg.get("departments", {})
    agents = reg.get("agents", {})
    keys = set(agents) | {"operator"}
    for key, a in agents.items():
        for field in REQUIRED_FIELDS:
            if field not in a or a[field] in (None, "", [], {}):
                errors.append(f"[{key}] missing field: {field}")
        if a.get("department") not in depts:
            errors.append(f"[{key}] unknown department: {a.get('department')}")
        if a.get("reports_to") not in keys:
            errors.append(f"[{key}] reports_to unknown agent: {a.get('reports_to')}")
        if "model" in a and a["model"].get("primary") not in TIER_TO_CLAUDE:
            errors.append(f"[{key}] unknown model tier: {a['model'].get('primary')}")
    for dkey, dval in depts.items():
        if dval.get("lead") not in agents:
            errors.append(f"[dept:{dkey}] lead not an agent: {dval.get('lead')}")
    return errors


def main() -> int:
    reg = load_registry()
    errors = validate(reg)
    if errors:
        print("Registry validation FAILED:")
        for e in errors:
            print("  -", e)
        return 1
    print(f"Registry OK: {len(reg['agents'])} agents, {len(reg['departments'])} departments.")

    if "--check" in sys.argv:
        return 0

    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    for key, a in reg["agents"].items():
        (AGENTS_DIR / f"{key}.md").write_text(render_subagent(key, a, reg["departments"]))
    CATALOG.write_text(render_catalog(reg))
    print(f"Wrote {len(reg['agents'])} subagents -> {AGENTS_DIR.relative_to(ROOT)}/")
    print(f"Wrote catalog -> {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
