#!/usr/bin/env python3
"""
Foundry — agent generator (Strong Agent Rubric).

Reads config/agents.yaml (registry) + config/agent_rubric.yaml (overlay) and renders:
  - .claude/agents/<key>.md    real Claude Code subagent definitions
  - docs/04-agent-catalog.md   human-readable catalog

Usage:
    python3 scripts/generate_agents.py           # generate
    python3 scripts/generate_agents.py --check   # validate only (CI-friendly)

Requires PyYAML (pip install pyyaml).
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "config" / "agents.yaml"
RUBRIC = ROOT / "config" / "agent_rubric.yaml"
AGENTS_DIR = ROOT / ".claude" / "agents"
CATALOG = ROOT / "docs" / "04-agent-catalog.md"

NL = chr(10)

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_agents.py from config/agents.yaml + "
    "config/agent_rubric.yaml. Do not edit by hand; edit the YAML and run `make agents`. -->"
)

# Abstract capability -> built-in Claude Code tools. Anything not here is an
# MCP/platform capability and is documented in the body instead of restricting
# the subagent to tools that may not exist yet.
BUILTIN_TOOL_MAP = {
    "read": ["Read", "Grep", "Glob"],
    "write": ["Write"],
    "edit": ["Edit"],
    "bash": ["Bash"],
    "research.web": ["WebSearch", "WebFetch"],
    "test.run": ["Bash"],
    "ci.run": ["Bash"],
}

# LangGraph/router tier -> Claude Code subagent `model` field. (In the local
# execution path these tiers map to Ollama models per config/models.yaml.)
TIER_TO_CLAUDE = {
    "local-small": "haiku",
    "local-mid": "sonnet",
    "local-large": "sonnet",
    "cloud-bulk": "sonnet",
    "cloud-reasoning": "sonnet",
    "cloud-frontier": "opus",
    "cloud-frontier-alt": "opus",
}

# Reviewer runs a DIFFERENT model than the author (rubric #10). Mirrors
# config/models.yaml reviewer_policy.default_reviewer_tier_for_author.
REVIEWER_TIER_FOR_AUTHOR = {
    "local-small": "cloud-reasoning",
    "local-mid": "cloud-frontier",
    "local-large": "cloud-frontier",
    "cloud-bulk": "cloud-frontier",
    "cloud-reasoning": "cloud-frontier",
    "cloud-frontier": "cloud-frontier-alt",
    "cloud-frontier-alt": "cloud-frontier",
}

REQUIRED_FIELDS = [
    "name", "department", "reports_to", "mission", "responsibilities",
    "inputs", "outputs", "authority", "escalation", "tools", "model", "memory",
    "examples",
]


def load_registry() -> dict:
    with REGISTRY.open() as f:
        return yaml.safe_load(f)


def load_rubric() -> dict:
    if RUBRIC.exists():
        with RUBRIC.open() as f:
            return yaml.safe_load(f) or {}
    return {}


def merge_rubric(reg: dict) -> None:
    """Overlay the rubric file onto each agent: model_override, non_goals,
    eval_threshold, and a derived reviewer (different model from the author)."""
    rubric = load_rubric()
    for key, a in reg["agents"].items():
        r = rubric.get(key, {}) or {}
        if isinstance(r.get("model_override"), dict):
            a["model"] = r["model_override"]
        a["non_goals"] = r.get("non_goals", [])
        a["eval_threshold"] = r.get("eval_threshold", 0.8)
        by = r.get("reviewer_by")
        gate = bool(r.get("reviewer_gate", False))
        author_tier = (a.get("model") or {}).get("primary", "local-mid")
        if by == "operator":
            rev_model = "human-operator"
        else:
            rev_model = REVIEWER_TIER_FOR_AUTHOR.get(author_tier, "cloud-frontier")
        a["reviewer"] = {"by": by, "model": rev_model, "gate": gate}


def builtin_tools_for(abstract_tools: list) -> list:
    out: list = []
    for t in abstract_tools:
        for mapped in BUILTIN_TOOL_MAP.get(t, []):
            if mapped not in out:
                out.append(mapped)
    if any(t.startswith("orchestrator") for t in abstract_tools):
        out.append("TodoWrite")
    if not out:  # read-only default
        out = ["Read", "Grep", "Glob"]
    return out


def md_list(items: list) -> str:
    return NL.join(f"- {i}" for i in items)


def render_subagent(key: str, a: dict, depts: dict) -> str:
    dept = depts.get(a["department"], {}).get("name", a["department"])
    author_tier = a["model"]["primary"]
    claude_model = TIER_TO_CLAUDE.get(author_tier, "sonnet")
    builtins = ", ".join(builtin_tools_for(a["tools"]))
    first_example = a["examples"][0] if a.get("examples") else "handle a scoped task in its domain"
    desc = f"{a['mission']} (Foundry - {dept}.) Use for: {first_example}"
    desc = desc.replace(NL, " ").replace(chr(34), "'")

    fallback = a["model"].get("fallback", "n/a")
    rev = a.get("reviewer") or {}
    rev_by = rev.get("by") or "n/a"
    rev_model = rev.get("model") or "n/a"
    rev_gate = "YES - output is not 'done' until the reviewer passes" if rev.get("gate") else "no"
    non_goals = a.get("non_goals") or []
    threshold = a.get("eval_threshold", 0.8)

    return f"""---
name: {key}
description: {desc}
tools: {builtins}
model: {claude_model}
---

{GENERATED_BANNER}

You are the **{a['name']}** at Foundry, a local-first AI software company.
You belong to the **{dept}** department. You report to **{a['reports_to']}**.

## Mission
{a['mission']}

## Responsibilities
{md_list(a['responsibilities'])}

## Inputs
{md_list(a['inputs'])}

## Outputs
{md_list(a['outputs'])}

## Decision authority
{a['authority']}

## Escalation path
{a['escalation']}

## Non-goals (you must NEVER)
{md_list(non_goals)}

## Tools & capabilities
Built-in tools granted above: `{builtins}`.
Platform/MCP capabilities this role uses (provided by the Foundry MCP servers):
`{', '.join(a['tools'])}`.

## Memory access
This role reads/writes these memory classes (see docs/06-memory-system.md):
`{', '.join(a['memory'])}`.
- Persist durable facts and decisions to memory - never raw chat transcripts.
- Check the decision log before re-deciding anything; cite the ADR if one exists.

## Model
- Router tier (local path): **{author_tier}** (fallback: **{fallback}**).
- Claude Code subagent model (this file): **{claude_model}**.

## Reviewer (rubric #10 - output is not done until this passes)
- Reviewed by: **{rev_by}** running model tier **{rev_model}** (a DIFFERENT model from this agent, to break correlated failure).
- Critical gate: **{rev_gate}**.

## Evaluation (rubric #9)
- Golden set: `evals/{key}/golden.yaml` (run with `make eval`).
- Eval-gated merge: changes must reach a pass-rate >= **{threshold}** before they count as done.

## Observability
- Every run emits a Langfuse trace, token cost, and eval pass-rate attributed to `{key}` (see docs/13).

## Operating rules (apply to every Foundry agent)
- Respect the **bright lines** - never merge to main, deploy to production, read/rotate
  a secret, spend money, run a destructive op, or modify policies **without explicit
  human approval** (config/policies.yaml). Local models stay on 127.0.0.1.
- Stay within your decision authority; when in doubt, escalate via the path above.
- Produce structured, verifiable outputs. State assumptions; report failures honestly.
- Never target third-party systems. Security testing is limited to Foundry-owned assets.
"""


def render_catalog(reg: dict) -> str:
    depts = reg["departments"]
    agents = reg["agents"]
    by_dept: dict = {d: [] for d in depts}
    for key, a in agents.items():
        by_dept.setdefault(a["department"], []).append(key)

    lines = [
        GENERATED_BANNER,
        "",
        "# 04 - Agent Catalog",
        "",
        f"The complete specification for every agent in **{reg['meta']['company']}** "
        f"(v{reg['meta']['version']}). Generated from `config/agents.yaml` + `config/agent_rubric.yaml`.",
        "",
        f"**{len(agents)} agents** across **{len(depts)} departments**. Each agent lists its "
        "mission, responsibilities, inputs, outputs, decision authority, escalation, non-goals, "
        "tools, model tier, memory, reviewer, eval set, and example tasks.",
        "",
        "> Runnable Claude Code subagents are in `.claude/agents/`; golden eval sets in `evals/<id>/`.",
        "",
        "## Summary table",
        "",
        "| Agent | Dept | Reports to | Model | Reviewer (model) | Gate |",
        "|---|---|---|---|---|---|",
    ]
    for key, a in agents.items():
        rev = a.get("reviewer") or {}
        gate = "yes" if rev.get("gate") else "-"
        lines.append(
            f"| `{key}` | {a['department']} | {a['reports_to']} | "
            f"{a['model']['primary']} | {rev.get('by', 'n/a')} ({rev.get('model', 'n/a')}) | {gate} |"
        )
    lines.append("")

    for dkey, dval in depts.items():
        keys = by_dept.get(dkey, [])
        if not keys:
            continue
        lines += ["", "---", "", f"## {dval['name']}", f"_Department lead: `{dval['lead']}`_", ""]
        for key in keys:
            a = agents[key]
            fb = a["model"].get("fallback", "n/a")
            rev = a.get("reviewer") or {}
            lines += [
                f"### {a['name']}  `({key})`",
                "",
                f"- **Mission:** {a['mission']}",
                f"- **Reports to:** `{a['reports_to']}`",
                "- **Responsibilities:**",
                *[f"  - {r}" for r in a["responsibilities"]],
                f"- **Inputs:** {'; '.join(a['inputs'])}",
                f"- **Outputs:** {'; '.join(a['outputs'])}",
                f"- **Decision authority:** {a['authority']}",
                f"- **Escalation:** {a['escalation']}",
                "- **Non-goals (never):**",
                *[f"  - {n}" for n in (a.get('non_goals') or [])],
                f"- **Tools:** `{', '.join(a['tools'])}`",
                f"- **Model:** primary `{a['model']['primary']}`, fallback `{fb}`",
                f"- **Reviewer:** `{rev.get('by', 'n/a')}` on `{rev.get('model', 'n/a')}`"
                f" (gate: {'yes' if rev.get('gate') else 'no'})",
                f"- **Eval set:** `evals/{key}/golden.yaml` (threshold {a.get('eval_threshold', 0.8)})",
                "- **Example tasks:**",
                *[f"  - {e}" for e in a["examples"]],
                "",
            ]
    return NL.join(lines) + NL


def validate(reg: dict) -> list:
    errors: list = []
    depts = reg.get("departments", {})
    agents = reg.get("agents", {})
    keys = set(agents) | {"operator"}
    for key, a in agents.items():
        for field in REQUIRED_FIELDS:
            if field not in a or a[field] in (None, "", [], {}):
                errors.append(f"[{key}] missing field: {field}")
        if a.get("department") not in depts:
            errors.append(f"[{key}] unknown department: {a.get('department')}")
        if a.get("reports_to") not in keys:
            errors.append(f"[{key}] reports_to unknown agent: {a.get('reports_to')}")
        author_tier = (a.get("model") or {}).get("primary")
        if author_tier not in TIER_TO_CLAUDE:
            errors.append(f"[{key}] unknown model tier: {author_tier}")
        # Rubric #4: explicit non-goals.
        ng = a.get("non_goals") or []
        if len(ng) < 3:
            errors.append(f"[{key}] non_goals: rubric #4 needs >=3, got {len(ng)} (add to agent_rubric.yaml)")
        # Rubric #10: assigned reviewer on a different model.
        rev = a.get("reviewer") or {}
        rby = rev.get("by")
        if not rby:
            errors.append(f"[{key}] reviewer.by missing (rubric #10; set reviewer_by in agent_rubric.yaml)")
        elif rby != "operator" and rby not in agents:
            errors.append(f"[{key}] reviewer.by unknown agent: {rby}")
        if rby and rby != "operator" and rev.get("model") == author_tier:
            errors.append(f"[{key}] reviewer must use a DIFFERENT model than author (rubric #10)")
    for dkey, dval in depts.items():
        if dval.get("lead") not in agents:
            errors.append(f"[dept:{dkey}] lead not an agent: {dval.get('lead')}")
    return errors


def main() -> int:
    reg = load_registry()
    merge_rubric(reg)
    errors = validate(reg)
    if errors:
        print("Registry/rubric validation FAILED:")
        for e in errors:
            print("  -", e)
        return 1
    print(f"Registry OK: {len(reg['agents'])} agents, {len(reg['departments'])} departments (rubric merged).")

    if "--check" in sys.argv:
        return 0

    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    for key, a in reg["agents"].items():
        (AGENTS_DIR / f"{key}.md").write_text(render_subagent(key, a, reg["departments"]))
    CATALOG.write_text(render_catalog(reg))
    print(f"Wrote {len(reg['agents'])} subagents -> {AGENTS_DIR.relative_to(ROOT)}/")
    print(f"Wrote catalog -> {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
