#!/usr/bin/env python3
"""
Foundry - agent generator (Strong Agent Rubric + governance).

Reads config/agents.yaml (+ config/agents_extra.yaml) and config/agent_rubric.yaml
(+ the `rubric:` block in agents_extra.yaml), and renders:
  - .claude/agents/<key>.md    real Claude Code subagent definitions
  - docs/04-agent-catalog.md   human-readable catalog

Usage:
    python3 scripts/generate_agents.py           # generate
    python3 scripts/generate_agents.py --check   # validate only (CI-friendly)

Requires PyYAML (pip install pyyaml).
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "config" / "agents.yaml"
EXTRA = ROOT / "config" / "agents_extra.yaml"
RUBRIC = ROOT / "config" / "agent_rubric.yaml"
AGENTS_DIR = ROOT / ".claude" / "agents"
CATALOG = ROOT / "docs" / "04-agent-catalog.md"

NL = chr(10)

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_agents.py from config/agents.yaml (+ "
    "agents_extra.yaml) + config/agent_rubric.yaml. Do not edit by hand; run `make agents`. -->"
)

BUILTIN_TOOL_MAP = {
    "read": ["Read", "Grep", "Glob"],
    "write": ["Write"],
    "edit": ["Edit"],
    "bash": ["Bash"],
    "research.web": ["WebSearch", "WebFetch"],
    "test.run": ["Bash"],
    "ci.run": ["Bash"],
}

TIER_TO_CLAUDE = {
    "local-small": "haiku",
    "local-mid": "sonnet",
    "local-large": "sonnet",
    "cloud-bulk": "sonnet",
    "cloud-reasoning": "sonnet",
    "cloud-frontier": "opus",
    "cloud-frontier-alt": "opus",
}

REVIEWER_TIER_FOR_AUTHOR = {
    "local-small": "cloud-reasoning",
    "local-mid": "cloud-frontier",
    "local-large": "cloud-frontier",
    "cloud-bulk": "cloud-frontier",
    "cloud-reasoning": "cloud-frontier",
    "cloud-frontier": "cloud-frontier-alt",
    "cloud-frontier-alt": "cloud-frontier",
}

REQUIRED_FIELDS = [
    "name", "department", "reports_to", "mission", "responsibilities",
    "inputs", "outputs", "authority", "escalation", "tools", "model", "memory",
    "examples",
]


def load_registry() -> dict:
    with REGISTRY.open() as f:
        return yaml.safe_load(f)


def merge_extra(reg: dict) -> None:
    """Merge the additive config/agents_extra.yaml (agents + departments)."""
    if not EXTRA.exists():
        return
    with EXTRA.open() as f:
        ex = yaml.safe_load(f) or {}
    reg.setdefault("agents", {}).update(ex.get("agents") or {})
    for dk, dv in (ex.get("departments") or {}).items():
        reg.setdefault("departments", {}).setdefault(dk, dv)


def load_rubric() -> dict:
    data: dict = {}
    if RUBRIC.exists():
        with RUBRIC.open() as f:
            data.update(yaml.safe_load(f) or {})
    if EXTRA.exists():
        with EXTRA.open() as f:
            ex = yaml.safe_load(f) or {}
        data.update(ex.get("rubric") or {})
    return data


def merge_rubric(reg: dict) -> None:
    rubric = load_rubric()
    for key, a in reg["agents"].items():
        r = rubric.get(key, {}) or {}
        if isinstance(r.get("model_override"), dict):
            a["model"] = r["model_override"]
        a["non_goals"] = r.get("non_goals", [])
        a["eval_threshold"] = r.get("eval_threshold", 0.8)
        by = r.get("reviewer_by")
        gate = bool(r.get("reviewer_gate", False))
        author_tier = (a.get("model") or {}).get("primary", "local-mid")
        rev_model = "human-operator" if by == "operator" else REVIEWER_TIER_FOR_AUTHOR.get(author_tier, "cloud-frontier")
        a["reviewer"] = {"by": by, "model": rev_model, "gate": gate}


def builtin_tools_for(abstract_tools: list) -> list:
    out: list = []
    for t in abstract_tools:
        for mapped in BUILTIN_TOOL_MAP.get(t, []):
            if mapped not in out:
                out.append(mapped)
    if any(t.startswith("orchestrator") for t in abstract_tools):
        out.append("TodoWrite")
    if not out:
        out = ["Read", "Grep", "Glob"]
    return out


def md_list(items: list) -> str:
    return NL.join(f"- {i}" for i in items)


def render_subagent(key: str, a: dict, depts: dict) -> str:
    dept = depts.get(a["department"], {}).get("name", a["department"])
    author_tier = a["model"]["primary"]
    claude_model = TIER_TO_CLAUDE.get(author_tier, "sonnet")
    builtins = ", ".join(builtin_tools_for(a["tools"]))
    first_example = a["examples"][0] if a.get("examples") else "handle a scoped task in its domain"
    desc = f"{a['mission']} (Foundry - {dept}.) Use for: {first_example}"
    desc = desc.replace(NL, " ").replace(chr(34), "'")

    fallback = a["model"].get("fallback", "n/a")
    rev = a.get("reviewer") or {}
    rev_by = rev.get("by") or "n/a"
    rev_model = rev.get("model") or "n/a"
    rev_gate = "YES - output is not 'done' until the reviewer passes" if rev.get("gate") else "no"
    non_goals = a.get("non_goals") or []
    threshold = a.get("eval_threshold", 0.8)
    exec_of = a["reports_to"]

    return f"""---
name: {key}
description: {desc}
tools: {builtins}
model: {claude_model}
---

{GENERATED_BANNER}

You are the **{a['name']}** at Foundry, a local-first AI software company.
You belong to the **{dept}** department. You report to **{exec_of}**.

## Mission
{a['mission']}

## Responsibilities
{md_list(a['responsibilities'])}

## Inputs
{md_list(a['inputs'])}

## Outputs
{md_list(a['outputs'])}

## Decision authority
{a['authority']}

## Escalation path
{a['escalation']}

## Chain of command (ask before acting)
- Your executive is **{exec_of}**. Before ANY side-effecting action (write, send, post, merge,
  deploy, spend), propose it and get **{exec_of}**'s approval first, then act. Reads, research,
  and drafts need no approval.
- BRIGHT LINES always require the operator (human), never an executive alone: merge to main,
  deploy to production, read/rotate a secret, spend money, destructive ops, modify policies,
  create/modify an agent, modify a skill/tool, publish or email externally, access customer PII,
  target third parties (config/policies.yaml).
- When in doubt, consult the `brain` agent and the vault before acting or escalating.

## Non-goals (you must NEVER)
{md_list(non_goals)}

## Tools & capabilities
Built-in tools granted above: `{builtins}`.
Platform/MCP capabilities this role uses (provided by the Foundry MCP servers):
`{', '.join(a['tools'])}`.

## Containment (least privilege)
- You run jailed to `~/foundry` (your workspace + the vault); you cannot touch the rest of the Mac.
  Network egress is default-deny - only hosts allowlisted for your domain may be reached
  (config/access.yaml).
- Secrets live in the n8n/Keychain broker, never on disk or in the vault; reading one is a human gate.

## Memory access
This role reads/writes these memory classes (see docs/06-memory-system.md):
`{', '.join(a['memory'])}`.
- Persist durable facts and decisions to memory - never raw chat transcripts.
- Check the decision log before re-deciding anything; cite the ADR if one exists.

## Brain & continuous learning
- Shared brain: the Obsidian-style vault at `vault/`. Read it for canon; when in doubt, ask `brain`.
- Persist durable facts/decisions to the vault + decision log (never raw chat). Personal notes are
  free; shared-canon edits are executive-gated.
- In free time, study your weakest eval area via the `learning-officer`'s path and log what you learn
  to the vault. Proposing a new skill/tool/agent is a human gate.

## Model
- Router tier (local path): **{author_tier}** (fallback: **{fallback}**).
- Claude Code subagent model (this file): **{claude_model}**.

## Reviewer (rubric #10 - output is not done until this passes)
- Reviewed by: **{rev_by}** running model tier **{rev_model}** (a DIFFERENT model from this agent, to break correlated failure).
- Critical gate: **{rev_gate}**.

## Evaluation (rubric #9)
- Golden set: `evals/{key}/golden.yaml` (run with `make eval`).
- Eval-gated merge: changes must reach a pass-rate >= **{threshold}** before they count as done.

## Observability
- Every action is logged to logs/activity/{key}.jsonl and traced (Langfuse: prompt, tokens, cost),
  viewable remotely over Tailscale (docs/18).

## How to do this job (operating doctrine)
You are replacing a human analyst; this is how they did the job (full text + living updates:
`vault/10-knowledge/how-to-do-this-job.md`). Generate freely, evaluate ruthlessly, iterate until an
evaluation pass comes back empty - the feeling of 'done' arrives at the end of writing, not of checking.
- **Read the request three ways** - what they literally said, what they want, what they need. Honor the
  literal ask as your contract, but if their theory of the fix is wrong the correction IS the deliverable,
  with evidence, never a silent substitution. Picture their next action before you start.
- **Externalize state in a ledger:** KNOWN (+ pointer to how you verified it) / ASSUMED (+ what would
  falsify it) / OPEN. A guess never becomes evidence by sitting on the page.
- **Recognition proposes; verification disposes.** 'I have seen this' is a hypothesis of zero authority.
  A real check can fail and is independent of what produced the belief. Prefer execution > independent
  derivation > consistency > re-reading; match the grade to the stakes.
- **Write a second hypothesis** before verifying the first, then hunt evidence that separates them, not
  evidence that merely fits. Verify at the edges (empty/zero/max/first/last/boundary) and verify anything
  from memory (flag names, signatures, stats) against source, not recall.
- **Surprise audit:** when a check passes exactly and effortlessly, confirm it actually exercised the
  thing you care about - a green light can be a check that never ran.
- **Reversibility sets the care bar, not difficulty.** Before anything irreversible or outward-facing
  (delete, deploy, spend, send, publish, message a person) ask your executive first and state what it
  will touch and why - the one check you are never senior enough to skip. Delete/remove is always an
  operator gate.
- **Keep three registers distinct** - observed / inferred / recommended - and calibrate words you will be
  audited on: 'confirmed' = you watched it, 'likely' = you would bet, 'possibly' = could not rule out.
  Do not launder inference into confidence or hedge facts into mush.
- **'I could not establish it' is a first-class answer** - with what you ruled out and what would settle
  it. A confident guess dressed as an answer detonates later with your name on it.
- **Before delivering, switch from author to adversary:** attack your load-bearing claim (is its evidence
  KNOWN or merely ASSUMED?), execute your own instructions literally, diff against the ORIGINAL request
  text, hunt self-contradiction, then audit every quotable number/name/date/verdict against source. One
  honest pass, fix what it catches, ship.

## Operating rules (apply to every Foundry agent)
- Respect the **bright lines** and the chain of command above - propose and get executive approval
  before side effects; the operator approves every bright line (config/policies.yaml). Local models
  stay on 127.0.0.1.
- Stay within your decision authority; when in doubt, ask `brain`, then escalate via the path above.
- Produce structured, verifiable outputs. State assumptions; report failures honestly.
- Never target third-party systems. Security testing is limited to Foundry-owned assets.
"""


def render_catalog(reg: dict) -> str:
    depts = reg["departments"]
    agents = reg["agents"]
    by_dept: dict = {d: [] for d in depts}
    for key, a in agents.items():
        by_dept.setdefault(a["department"], []).append(key)

    lines = [
        GENERATED_BANNER,
        "",
        "# 04 - Agent Catalog",
        "",
        f"Every agent in **{reg['meta']['company']}** (v{reg['meta']['version']}). Generated from "
        "config/agents.yaml (+ agents_extra.yaml) + config/agent_rubric.yaml.",
        "",
        f"**{len(agents)} agents** across **{len(depts)} departments**.",
        "",
        "| Agent | Dept | Reports to | Model | Reviewer (model) | Gate |",
        "|---|---|---|---|---|---|",
    ]
    for key, a in agents.items():
        rev = a.get("reviewer") or {}
        gate = "yes" if rev.get("gate") else "-"
        lines.append(
            f"| `{key}` | {a['department']} | {a['reports_to']} | "
            f"{a['model']['primary']} | {rev.get('by', 'n/a')} ({rev.get('model', 'n/a')}) | {gate} |"
        )
    lines.append("")
    for dkey, dval in depts.items():
        keys = by_dept.get(dkey, [])
        if not keys:
            continue
        lines += ["", "---", "", f"## {dval['name']}", f"_Department lead: `{dval['lead']}`_", ""]
        for key in keys:
            a = agents[key]
            rev = a.get("reviewer") or {}
            lines += [
                f"### {a['name']}  `({key})`",
                "",
                f"- **Mission:** {a['mission']}",
                f"- **Reports to:** `{a['reports_to']}` (ask-before-acting)",
                "- **Non-goals (never):**",
                *[f"  - {n}" for n in (a.get('non_goals') or [])],
                f"- **Tools:** `{', '.join(a['tools'])}`",
                f"- **Model:** `{a['model']['primary']}` / reviewer `{rev.get('by', 'n/a')}` on `{rev.get('model', 'n/a')}` (gate: {'yes' if rev.get('gate') else 'no'})",
                f"- **Eval set:** `evals/{key}/golden.yaml` (threshold {a.get('eval_threshold', 0.8)})",
                "",
            ]
    return NL.join(lines) + NL


def validate(reg: dict) -> list:
    errors: list = []
    depts = reg.get("departments", {})
    agents = reg.get("agents", {})
    keys = set(agents) | {"operator"}
    for key, a in agents.items():
        for field in REQUIRED_FIELDS:
            if field not in a or a[field] in (None, "", [], {}):
                errors.append(f"[{key}] missing field: {field}")
        if a.get("department") not in depts:
            errors.append(f"[{key}] unknown department: {a.get('department')}")
        if a.get("reports_to") not in keys:
            errors.append(f"[{key}] reports_to unknown agent: {a.get('reports_to')}")
        author_tier = (a.get("model") or {}).get("primary")
        if author_tier not in TIER_TO_CLAUDE:
            errors.append(f"[{key}] unknown model tier: {author_tier}")
        ng = a.get("non_goals") or []
        if len(ng) < 3:
            errors.append(f"[{key}] non_goals: rubric #4 needs >=3, got {len(ng)}")
        rev = a.get("reviewer") or {}
        rby = rev.get("by")
        if not rby:
            errors.append(f"[{key}] reviewer.by missing (rubric #10)")
        elif rby != "operator" and rby not in agents:
            errors.append(f"[{key}] reviewer.by unknown agent: {rby}")
        if rby and rby != "operator" and rev.get("model") == author_tier:
            errors.append(f"[{key}] reviewer must use a DIFFERENT model than author (rubric #10)")
    for dkey, dval in depts.items():
        if dval.get("lead") not in agents:
            errors.append(f"[dept:{dkey}] lead not an agent: {dval.get('lead')}")
    return errors


def main() -> int:
    reg = load_registry()
    merge_extra(reg)
    merge_rubric(reg)
    errors = validate(reg)
    if errors:
        print("Registry/rubric validation FAILED:")
        for e in errors:
            print("  -", e)
        return 1
    print(f"Registry OK: {len(reg['agents'])} agents, {len(reg['departments'])} departments (extra + rubric merged).")
    if "--check" in sys.argv:
        return 0
    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    for key, a in reg["agents"].items():
        (AGENTS_DIR / f"{key}.md").write_text(render_subagent(key, a, reg["departments"]))
    CATALOG.write_text(render_catalog(reg))
    print(f"Wrote {len(reg['agents'])} subagents -> {AGENTS_DIR.relative_to(ROOT)}/")
    print(f"Wrote catalog -> {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
